### ISSUE TITLE
Always use `is_ci()` instead of `IS_CI`?

### ISSUE THREAD

**Issue by findmyway** [JuliaBooks/Books.jl#245] opened 2021-11-09 05:03 UTC
I find that `IS_CI` is defined as a constant in this package:

https://github.com/JuliaBooks/Books.jl/blob/93376d98db5de7425bddd2659f07685d6a90f84a/src/ci.jl#L1-L2

I'm afraid this is not the standard way to do so.

The `IS_CI` is defined as a `const`, which means it will be precompiled and will never be changed later. The direct result is that users can not modify it by setting the `CI` environment variable to test the local building pipeline.

I'd recommend using `is_ci()` instead of `IS_CI` throughout this package.

<hr>

I suspect this is the root cause of the incorrect rendering of https://cn.julialang.org/JuliaDataScience/ . (The `online_url_prefix ` is [added](https://github.com/JuliaCN/JuliaDataScience/commit/f92c60c15054b543bf344fd39890b899fe032ca3) but it doesn't take into effect)

**Comment by rikhuijzer** [comment] 2021-11-09 07:44
> I suspect this is the root cause of the incorrect rendering of https://cn.julialang.org/JuliaDataScience/ . (The online_url_prefix is added but it doesn't take into effect)

The issue is actually #241. It's fixed in `main`, but I didn't tag it yet. I'll tag a new Books version now.

**Comment by rikhuijzer** [comment] 2021-11-09 07:47
I don't see why defining `IS_CI` a const is a problem. Either you're on a CI machine or you're not and I personally didn't have the need to switch the var after starting.

So, I close this issue for now and the related PR #246 for now. Feel free to reopen.

**Comment by findmyway** [comment] 2021-11-09 08:44
Thanks!

**Closed** 2021-11-09 08:43 UTC
